### ISSUE TITLE
setState() or markNeedsBuild() called during build.

### ISSUE THREAD

**Issue by BoomPowbep** [pedromassango/titled_navigation_bar#9]
The callback I provided to `onTap` has a `setState()` in it. It works just great with the classic `BottomNavigationBar` but it doesn't with `TitledBottomNavigationBar`. 

I get the error `setState() or markNeedsBuild() called during build.`

```
void _onTabTapped(int index) {
    setState(() {
      if (index == 0) {
        _scaffoldKey.currentState.openDrawer();
      } else {
        _currentIndex = index;
      }
    });
  }

  /// Construit le widget
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      /*****/
      bottomNavigationBar: TitledBottomNavigationBar(
        onTap: (i) => _onTabTapped(i),
        initialIndex: 1,
        reverse: true,
        activeColor: Colors.black,
        currentIndex: _currentIndex,
        items: [
         /******/
        ],
      ),
    );
  }
```

This is the full error (which I think is not that relevant...) : 
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building MediaQuery(MediaQueryData(size: Size(375.0, 667.0),
flutter: devicePixelRatio: 2.0, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding:
flutter: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation:
flutter: falsedisableAnimations: falseinvertColors: falseboldText: false)):
flutter: setState() or markNeedsBuild() called during build.
flutter: This Home widget cannot be marked as needing to build because the framework is already in the
flutter: process of building widgets. A widget can be marked as needing to be built during the build phase
flutter: only if one of its ancestors is currently building. This exception is allowed because the framework
flutter: builds parent widgets before children, which means a dirty descendant will always be built.
flutter: Otherwise, the framework might not visit this widget during this build phase.
flutter: The widget on which setState() or markNeedsBuild() was called was:
flutter:   Home(state: _HomeState#c3616)
flutter: The widget which was currently being built when the offending call was made was:
flutter:   MediaQuery(MediaQueryData(size: Size(375.0, 667.0), devicePixelRatio: 2.0, textScaleFactor: 1.0,
flutter:   platformBrightness: Brightness.light, padding: EdgeInsets.zero, viewInsets: EdgeInsets.zero,
flutter:   alwaysUse24HourFormat: false, accessibleNavigation: falsedisableAnimations: falseinvertColors:
flutter:   falseboldText: false))
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3503:11)
flutter: #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3529:6)
flutter: #2      State.setState (package:flutter/src/widgets/framework.dart:1133:14)
flutter: #3      _HomeState._onTabTapped (package:leonor_greyl_app_2019_41820/Home.dart:50:5)
flutter: #4      _HomeState.build.<anonymous closure> (package:leonor_greyl_app_2019_41820/Home.dart:73:23)
flutter: #5      _TitledBottomNavigationBarState._select (package:titled_navigation_bar/src/navigation_bar.dart:122:12)
flutter: #6      _TitledBottomNavigationBarState.initState (package:titled_navigation_bar/src/navigation_bar.dart:58:5)
flutter: #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
flutter: #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
flutter: #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #13     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #17     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #19     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
flutter: #20     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #24     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #28     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #32     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #38     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #44     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #48     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #52     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #60     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #64     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #70     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #72     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #74     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #76     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
flutter: #77     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #81     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #87     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #89     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #93     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #95     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #99     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #103    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #107    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #109    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #113    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #115    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #119    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #123    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #125    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #128    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #129    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #132    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #133    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
flutter: #134    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
flutter: #135    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #136    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #137    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
flutter: #138    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
flutter: #140    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
flutter: #141    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
flutter: #142    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
flutter: (elided one frame from package dart:async-patch)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by magixyu** [comment]
Change your onTap call to below. The setState is called by this widget already. If you have setState, you get it called nested.

`dart
void _onTabTapped(int index) {
      if (index == 0) {
        _scaffoldKey.currentState.openDrawer();
      } else {
        _currentIndex = index;
      }
  }
`

**Comment by pedromassango** [comment]
@BoomPowbep You don't need setState() as said by @magixyu . Maybe I must explain it in README.

I'm going to close this for now. Feel free to open it later.

**Comment by alike010000** [comment]
This should work.
```dart
return Scaffold(
      body: _screens[_currentIndex],
      bottomNavigationBar: TitledBottomNavigationBar(
        currentIndex: _currentIndex,
        onTap: (int index) {
          if (_currentIndex != index) {
            setState(() {
              _currentIndex = index;
            });
          }
        },
        items: [
          TitledNavigationBarItem(title: 'Home', icon: Icons.home),
          TitledNavigationBarItem(title: 'settings', icon: Icons.settings)
        ],
      ),
    );
```
